### ISSUE TITLE
bugs when the .doc file

### ISSUE THREAD

**Issue by gaoguoxin** [mime-types/ruby-mime-types#114]
```ruby
require 'mime/types'
guesses = MIME::Types.type_for('abc.doc')
#=> [application/msword, application/word, application/x-msword, application/x-word, text/plain]
guesses.detect { |type| type.ascii? }
#=>text/plain
```
as you can see the return value should application/msword

**Comment by halostatue** [comment]
Actually…this isn’t a bug. The files in question *are* binary, not *text* (`#ascii?`):

```
10:30:53 >> guesses = MIME::Types.type_for('abc.doc')
=> [#<MIME::Type: application/msword>,
 #<MIME::Type: application/word>,
 #<MIME::Type: application/x-msword>,
 #<MIME::Type: application/x-word>,
 #<MIME::Type: text/plain>]
10:31:04 >> guesses.map(&:encoding)
=> ["base64", "base64", "base64", "base64", "quoted-printable"]
```

The only `#ascii?` encodings are `7bit` and `quoted-printable`. This information is historical and does not mean what you think it means, only indicating that the wire transport for these are either 7bit clean (strict US-ASCII with no high bits turned on) or [quoted-printable](https://en.wikipedia.org/wiki/Quoted-printable).

See also [8-bit clean](https://en.wikipedia.org/wiki/8-bit_clean).
