### ISSUE TITLE
test failure

### ISSUE THREAD

**Issue by wwood** [mime-types/ruby-mime-types#118]
Hi,

I just came across this test error:
```
  1) Error:
MIME::Types::Cache::.load#test_0003_outputs an error when there is an invalid version:
RuntimeError: can't modify frozen String
    /tmp/nix-build-ruby-mime-types-3.0.drv-0/gem/test/test_mime_types_cache.rb:40:in `gsub!'
    /tmp/nix-build-ruby-mime-types-3.0.drv-0/gem/test/test_mime_types_cache.rb:40:in `block (3 levels) in <top (required)>'

143 runs, 271 assertions, 0 failures, 1 errors, 0 skips
```
Any ideas? This is using gem v3.0, but this line of code is still in master too. This is using Ruby 2.3.1.

Thanks.

**Comment by halostatue** [comment]
Yeah. I have a fix for this coming shortly.

**Comment by halostatue** [comment]
This is now fixed on mime-types-3.1-pre which should be released as mime-types 3.1 tomorrow.

**Comment by wwood** [comment]
Great, thanks.

**Comment by halostatue** [comment]
mime-types 3.1 has been released with a fix for this issue.
