### ISSUE TITLE
Markdown returns wrong content-type.

### ISSUE THREAD

**Issue by envygeeks** [mime-types/ruby-mime-types#133]
See: https://tools.ietf.org/html/rfc7763

<img width="969" alt="image" src="https://user-images.githubusercontent.com/99763/40466029-521c8b24-5ee9-11e8-9dc3-7cdaa9f374f9.png">

**Comment by halostatue** [comment]
Related to mime-types/mime-types-data#15

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
