### ISSUE TITLE
rdoc out of date

### ISSUE THREAD

**Issue by nirvdrum** [mime-types/ruby-mime-types#152]
I followed the [rdoc link](http://rdoc.info/gems/mime-types) from the README and found that the code samples in the "Synopsis" section are wrong. It looks like same sample appears directly in the README, updated and working, so I think the rdoc.info site just wasn't refreshed.

**Comment by halostatue** [comment]
Unfortunately, I don’t have control over the generation of the code, and rdoc.info also uses the wrong code generator (it uses YARD, not RDoc; there are features that YARD incorrectly refuses to implement).

Should a new release be made, it is possible the that examples will be generated. This can be checked against https://rdoc.info/github/mime-types/ruby-mime-types/master.
