### ISSUE TITLE
MIME::Type defines #eql? but not #hash

### ISSUE THREAD

**Issue by ajvondrak** [mime-types/ruby-mime-types#166]
We've been experiencing the warning described by #163 + mime-types/mime-types-data#50 about the duplicate `application/netcdf` variant. However, as in #163, the warning was only intermittent. Most of the time we get no warning at all!

The message is generated by this check: https://github.com/mime-types/ruby-mime-types/blob/5b931d70d74f3d1ba25babac03237ae450ca5c5b/lib/mime/types.rb#L189-L193 where `@type_variants` is a hash from `String` to `Set`.

I set up a breakpoint in that block and finally managed to catch the two states (warning vs no warning) to compare them. The difference was that the `Set#include?` was returning `true` in one case but `false` in the other.

I managed to distill the scenario into this repro script:

```ruby
require 'mime/types'

N = 1_000

N.times do |n|
  a = MIME::Type::Columnar.new(nil, 'application/netcdf', [])
  b = MIME::Type::Columnar.new(nil, 'application/netcdf', ['nc', 'cdf'])
  if Set[a].include?(b)
    puts "warning after #{n.succ} tries"
    exit
  end
end

puts "no warning after #{N} tries"
```

```console
$ for _ in $(seq 10); do ruby repro.rb; done
warning after 128 tries
warning after 135 tries
no warning after 1000 tries
no warning after 1000 tries
no warning after 1000 tries
warning after 58 tries
no warning after 1000 tries
warning after 115 tries
warning after 66 tries
warning after 246 tries
```

What's happening under the hood is actually that `Set` is backed by a `Hash`, and `MIME::Type` is using the default implementation of `Object#hash`, even though it overrides `#eql?`. Per [Ruby's docs](https://ruby-doc.org/core-3.1.2/Object.html#method-i-eql-3F):

> The `eql?` method returns `true` if `obj` and `other` refer to the same hash key. This is used by `Hash` to test members for equality. For any pair of objects where `eql?` returns `true`, the `hash` value of both objects must be equal. So any subclass that overrides `eql?` should also override `hash` appropriately.

What they _don't_ tell you is the weird behavior you'll get if you don't follow through on this contract. 😄 Tweaking the repro script, we see the same basic behavior without touching the mime-types gem at all:

```ruby
class Test
  def eql?(other)
    true
  end
end

N = 1_000

N.times do |n|
  a = Test.new
  b = Test.new
  if { a => true }.include?(b)
    puts "collision after #{n.succ} tries"
    exit
  end
end

puts "no collision after #{N} tries"
```

```console
$ for _ in $(seq 10); do ruby repro.rb; done
collision after 609 tries
no collision after 1000 tries
no collision after 1000 tries
no collision after 1000 tries
collision after 64 tries
collision after 50 tries
no collision after 1000 tries
no collision after 1000 tries
collision after 76 tries
collision after 230 tries
```

Looking at the definition of the `MIME::Type#<=>` method, I _think_ a reasonable implementation of `#hash` would be based on the class + the `#simplified` value. Plugging that into the original repro script:

```ruby
require 'mime/types'

class MIME::Type
  def hash
    [self.class, simplified].hash
  end
end

N = 1_000

N.times do |n|
  a = MIME::Type::Columnar.new(nil, 'application/netcdf', [])
  b = MIME::Type::Columnar.new(nil, 'application/netcdf', ['nc', 'cdf'])
  if Set[a].include?(b)
    puts "warning after #{n.succ} tries"
    exit
  end
end

puts "no warning after #{N} tries"
```

```console
$ for _ in $(seq 10); do ruby repro.rb; done
warning after 1 tries
warning after 1 tries
warning after 1 tries
warning after 1 tries
warning after 1 tries
warning after 1 tries
warning after 1 tries
warning after 1 tries
warning after 1 tries
warning after 1 tries
```

This does **not** solve the issue of there being duplicates for the `application/netcdf` data. However, it would actually make the warning deterministic, rather than having it crop up at random.

**Comment by halostatue** [comment]
I would accept a PR for this, no problem. I have no time to implement it myself, though.
