### ISSUE TITLE
Provide logical categories for mime-types for convenience.

### ISSUE THREAD

**Issue by ioquatix** [mime-types/ruby-mime-types#45]
As per the discussion in https://github.com/ioquatix/utopia/issues/1

It would be good if `MIME::Types.of(:archive)` would provide common, non-obsolete archive types.

In addition, providing a way to expand mime types based on a standard format might be nice, e.g. something similar to

``` ruby
MIME_TYPES = {
  :xiph => {
    "ogx" => "application/ogg",
    "ogv" => "video/ogg",
    "oga" => "audio/ogg",
    "ogg" => "audio/ogg",
    "spx" => "audio/ogg",
    "flac" => "audio/flac",
    "anx" => "application/annodex",
    "axa" => "audio/annodex",
    "xspf" => "application/xspf+xml",
  },
  :media => [
    :xiph, "mp3", "mp4", "wav", "aiff", ["aac", "audio/x-aac"], "mov", "avi", "wmv", "mpg"
    ],
  :text => [
    "html", "css", "js", "txt", "rtf", "xml", "pdf"
    ],
  :fonts => [
    "otf", ["eot", "application/vnd.ms-fontobject"], "ttf", "woff"
    ],
  :archives => [
    "zip", "tar", "tgz", "tar.gz", "tar.bz2", ["dmg", "application/x-apple-diskimage"],
  ["torrent", "application/x-bittorrent"]
    ],
  :images => [
    "png", "gif", "jpeg", "tiff", "svg"
    ],
  :default => [
    :media, :text, :archives, :images, :fonts
    ]
}
```

Being able to write:

``` ruby
MIME::Types.expand(MIME_TYPES) {|type| ... }
```

Could be very useful. Propose that we use a similar method for expansion, based on Utopia, the code here: https://github.com/ioquatix/utopia/blob/master/lib/utopia/middleware/static.rb#L160-L200

``` ruby
def load_mime_types(types)
  result = {}

  extract_extensions = lambda do |mime_type|
  # LOG.info "Extracting #{mime_type.inspect}"
  mime_type.extensions.each{|ext| result["." + ext] = mime_type.content_type}
  end

  types.each do |type|
    current_count = result.size
    # LOG.info "Processing #{type.inspect}"

    begin
      case type
      when Symbol
        result = load_mime_types(MIME_TYPES[type]).merge(result)
      when Array
        result["." + type[0]] = type[1]
      when String
        mt = MIME::Types.of(type).select{|mt| !mt.obsolete?}.each do |mt|
          extract_extensions.call(mt)
        end
      when Regexp
        MIME::Types[type].select{|mt| !mt.obsolete?}.each do |mt|
          extract_extensions.call(mt)
        end
      when MIME::Type
        extract_extensions.call(type)
      end
    rescue
      LOG.error "#{self.class.name}: Error while processing #{type.inspect}!"
      raise $!
    end

    if result.size == current_count
      LOG.warn "#{self.class.name}: Could not find any mime type for #{type.inspect}"
    end
  end

  return result
end
```

In addition, allowing a user to customise the way this expansion work could be a good idea to ensure that a user can lock in specific behaviour. But then alternatively, the user could lock in a specific version of mime-types gem which would serve the same purpose. However, it should still be possible for the user to adjust the way expansions works by appending or amending types as required.

**Comment by ioquatix** [comment]
This looks awesome, is this currently in the released gem?

**Comment by halostatue** [comment]
Not yet. I have been…distracted since before RubyConf. I hope to get back to this soon.

**Comment by ioquatix** [comment]
I finally extracted the functionality out of the middleware. This might be useful. It could load things on-demand too which would be pretty sweet.

https://github.com/ioquatix/utopia/blob/14bf541b168f95600d276584625bb1080798c503/lib/utopia/static.rb#L32-L114

This obviously isn't a PR, but I'm just reigniting this discussion with a fresh slice of code.

**Comment by halostatue** [comment]
Excellent, thanks. I think I need to update the milestone for this for the future, but I honestly have not forgotten this.

Great work, BTW, on your Accept-* parsing library. I suspect we are going to be using it ourselves.

**Comment by ioquatix** [comment]
Nice, what do you plan to use it for?

**Comment by halostatue** [comment]
We’re doing polymorphic resource versioning on an endpoint. (All of the resources are linked “content”, but have representations both internally and externally which vary based on the needs of the client.)
