### ISSUE TITLE
Make RUBY_MIME_TYPES_LAZY_LOAD the default

### ISSUE THREAD

**Issue by halostatue** [mime-types/ruby-mime-types#62]
Although loading the MIME type registry is fairly fast, do not force people to pay that cost up front. Implement `ENV['RUBY_MIME_TYPES_LAZY_LOAD']` as the default behaviour and provide a new variable (`ENV['RUBY_MIME_TYPES_IMMEDIATE_LOAD']`) to fall back to the old behaviour.

**Comment by halostatue** [comment]
This would be fairly useful, but there is not much of a definable benefit to this as a default. I will do further investigation on this, but I think that I am more likely to look at removing the lazy load functionality entirely for mime-types 4.x because of the columnar capabilities added in 2.6 and improved in 3.0.

**Comment by grosser** [comment]
came here because I noticed 0.3s of my boot time going into mime-types :(

used this flag and ran 1 test each ... only showing 0.1s gain, but that might be because the files are hot/cached at this point, so not sure about the real gain but it is a step in the right direction ..

```
RUBY_MIME_TYPES_LAZY_LOAD=true
runs: 10
total: 53.86
average: 5.39
range: 5.27..5.82

without:
runs: 10
total: 54.48
average: 5.45
range: 5.35..5.54
```

**Comment by halostatue** [comment]
You should also look at using `require: 'mime/types/columnar'` in your Gemfile since you appear to be stuck on 2.99.x, which will do a *different* form of lazy loading (columnar, so you get fast lookups for minimal data). The other advantage on this is that it will drop the memory of use MIME::Types by about 1/3. I am trying to get rest-client to loosen the MIME::Types version they require so that MIME::Types 3 can be used (it allows for independent updating of the data file), and the zendesk_api should probably do the same.

**Comment by grosser** [comment]
that would be awesome :)

**Comment by halostatue** [comment]
As previously discussed: this is being deprecated. Some testing suggests that it has no effective impact compared to the columnar loading that is the default version in v3.
