### ISSUE TITLE
Include the public cert?...

### ISSUE THREAD

**Issue by ToadJamb** [mime-types/ruby-mime-types#78]
```
The gem mime-types-2.4.3 can't be installed because the security policy didn't allow it, with the message: root cert /CN=austin/DC=rubyforge/DC=org is not trusted
```

When installing mime-types using high security, I am notified that version 2.4.3 cannot be installed because of an untrusted cert, but I can find no trace of the public cert. Did I miss it?

**Comment by todb** [comment]
:+1: 

Kind of a bummer that the cert is missing completely. Does it exist anywhere as a gist or something?

```
The gem mime-types-2.4.3 can't be installed because the security policy didn't allow it, with the
message: certificate /CN=austin/DC=rubyforge/DC=org not valid after 2015-02-22 03:41:43 UTC
```

Note that this issue blocks installing anything that includees mime-types in a bundle that wishes to use `--trust-policy MediumSecurity`

cc @claudijd and @bturner-r7

**Comment by todb-r7** [comment]
Oh, my mistake, it's 2.4.3 that's requiring a cert, the current release does not.

Now, who in my gemspec is requiring 2.4.3....
