### ISSUE TITLE
Switch entirely to MIT (or ISC) licence for MIME-Types 3.x

### ISSUE THREAD

**Issue by halostatue** [mime-types/ruby-mime-types#95]
I should have done this for version 2.x, but I didn’t. The API for the `mime-types` gem is substantially different than the original Perl version, and with discussions in #94, it’s pretty clear to me that version 3 is going to be throwing out a lot of older code with newer code that I have written.

Git shows me 289 commits, 265 of which are content (non-merge) commits. 28 of these are commits related to maintenance at RubyForge (CSV and SVN management) or importing to GitHub (all 22 by Tom Copeland, all 4 by `(no author)`, the one by Todd Carrico, and the one by `unknown`). 192 are by me, so those aren’t a problem.

I do not need to get license-change permission from people who have only made data registry changes, as the copyright on this is *at best* a collection copyright and I am mirroring data that is otherwise publicly available. That eliminates the following commit collections:

* [x] 11 commits by Andre Pankratz (@punkrats): 21fb3b0, 7574cc2, b13fc8d, 9c948fc, bd0d368, 85242b6, e2ba87b, 5870346, a658142, a2be11e, and bd91208.
* [x] 8 commits by Garret Alfert (@galfert): 3d6fea0, 39a5451, 3febfe9, c17d093, a56b580, c346622, 521c0b1, and 126f776.
* [x] 1 commit by Postmodern (@postmodern): 50c2f2d
* [x] 2 commits by Keerthi Siva (@keerthisiv): ba595c1 and 28ef3db
* [x] 1 commit by Hans de Graaf (@graaff): 70b1ee3
* [x] 1 commit by Martin d'Allens (@caerbannog): 21279dd
* [x] 1 commit by Mauricio Linhares (@mauricio): a502a44
* [x] 1 commit by Richard Hurt (@mhurt): f22d5be
* [x] 1 commit by Richard Hirner (@rfc2822): 664767c
* [x] 1 commit by Aggelos Aversions (@eavgarinos): 1b58a0a
* [x] 1 commit by Andy Brody (@ab): cc9f602
* [x] 1 commit by Brandon Galbraith (@brandongalbraith): 8cb6fcd
* [x] 1 commit by Chris Gat (@cgat): 876519b
* [x] 1 commit by Eric Marden (@xentek): 71f3d97

I am also excluding these commits because they are configuration-only:

* [x] 1 commit by Juanito Fatas (@JuanitoFatas): fdb66c0
* [x] 1 commit by @nycvotes-dev: d96b070 (this one also had to be rewritten to work with Hoe)

**Comment by halostatue** [comment]
This leaves me needing accession from the following individuals for their commits either to the software or its immediately related documentation:

* [ ] 3 commits by Arnaud Meuret (@ameuret): 6c58df4 644259d, and fd53425
* [ ] 2 commits by Postmodern (@postmodern): 36675e0 and e1061c6
* [ ] 1 commit by Henrik Hodne (@henrikhodne): 8987d9f
* [ ] 1 commit by Tibor Szolár (@flexik): 5c99074
* [ ] 1 commit by Richard Schneeman (@schneems): 3aad222
* [ ] 1 commit by Aaron Patterson (@tenderlove): 2fc2cd7
* [ ] 1 commit by David Genord II (@albus522): bf46fc7
* [ ] 1 commit by Godfrey Chan (@chancancode): 961846c

**Comment by chancancode** [comment]
I consent! 👍💛💙💜💚❤️

**Comment by postmodern** [comment]
MIT, BSD or LGPL.

**Comment by henrikhodne** [comment]
MIT or ISC is okay with me :+1:

**Comment by flexik** [comment]
Fine by me. :+1:

**Comment by punkrats** [comment]
Even though my commits are not relevant, I'm happy with any liberal license. :)

**Comment by schneems** [comment]
Works for me, most all of my work is MIT :+1:

**Comment by albus522** [comment]
Fine by me

**Comment by tenderlove** [comment]
I'm fine with it.

**Comment by ameuret** [comment]
MIT FTW ! ✌🏻️

**Comment by halostatue** [comment]
Hoorah! MIME::Types 3.0 will be MIT-licensed only.

**Comment by halostatue** [comment]
While not yet released, the mime-types-3.0 branch is already MIT only.
